### ISSUE TITLE
Gulp...

### ISSUE THREAD

**Issue by gwilymgj** [dwightwatson/neontsunami-laravel#1]
Hi there - any chance you could put a few details on how you run your gulp implementation to publish assets / watch for less changes ? :-)

**Comment by dwightwatson** [comment]
Yeah nice idea, I'll try and get onto this a little later today.

**Comment by dwightwatson** [comment]
Added some details on how I've got Gulp and Envoy set up, hope this it's helpful. Feel free to shoot any questions my way.
