### ISSUE TITLE
Plain encryption key?

### ISSUE THREAD

**Issue by afraca** [dwightwatson/neontsunami-laravel#2]
Although security through obscurity is a malpractice, I guess we shouldn't make it too easy for people. On: 

https://github.com/dwightwatson/neontsunami/blob/master/app/config/app.php#L81 

There's the plain encryption key used for Auth. Might be nice to put in in some .env. file?

**Comment by dwightwatson** [comment]
Good call, I've moved the encryption key into an environment variable.

**Comment by afraca** [comment]
Forgive me for being annoying, but technically you should regenerate your key as it's already been compromised. But beware!! All passwords hashed in the database will become unavailable when regenerating your key. If that is a problem, you need to set up a migration path where you use the new key for new logins and slowly replace it and stuff. Well, have fun with it ;)

**Comment by dwightwatson** [comment]
Not annoying at all! Yeah I went straight ahead and generated a new key for the production site. 

I'm not sure the encryption key affects hashed passwords though, Laravel's hasher uses an implementation of a Bcrypt which handles the salting and hashing of content internally.

**Comment by afraca** [comment]
You are right. I had an incorrect memory of reading the key was also used in the hashing steps. I haven't really looked into the implementation of Bcrypt, that's why I thought it was plausible. I looked it up and the key is not used.
